### PR TITLE
Regen APIs

### PR DESCRIPTION
**Pull request by tcoffee-google**

### CODE REVIEW

**Comment by vchudnov-g** [comment]
AFAICT, LGTM, but wait for @sqrrrl to approve as well.

And let's document the process for pushing the resulting gems.

**Comment by tcoffee-google** [comment]
@sqrrrl ping

**Comment by sqrrrl** [comment]
Can you add adexchangebuyer2:v2beta1 and regen while you're at it?

**Comment by tcoffee-google** [comment]
Done. Was it the intention to give us permissions to push the gem update? My Github credentials get rejected.

**Comment by sqrrrl** [comment]
Thomas - See http://guides.rubygems.org/publishing/#publishing-to-rubygemsorg

I just added googleapis-packages@google.com as an owner, but if you're using a different account to push to rubygems LMK and I'll add it as an owner too.

**Comment by tcoffee-google** [comment]
I was just trying to use my own account, tcoffee-google.

**Comment by vchudnov-g** [comment]
Let's stick with googleapis-packages@ for now. I'm inquiring about the
credentials we need for that account on rubygems.org

Thomas, I sent you a separate email on adding yourself to that internal
group, though that has no bearing on being able to use on rubygems.org.

**Comment by tcoffee-google** [comment]
@sqrrrl are we okay to merge on Github? This is all we need for our checks to pass.

**Pull request merged**
