### PR TITLE
Add samples of gmail

### PR DESCRIPTION
**Pull request by ts-3156**
Hello,

Thank you for useful gem!!
I added samples of gmail. Let me know if there's anything wrong with this PR.

Thanks!

### CODE REVIEW

**Comment by ts-3156** [comment]
I signed it!

**Comment by sqrrrl** [comment]
Mostly fine, but suggest dropping the use of 2.3 language features. 2.3 adoption is still less than older 2.x versions.

**Comment by ts-3156** [comment]
Hello, @sqrrrl 

Thank you for replying.

> dropping the use of 2.3 language features.

OK. I will fix it.

**Comment by ts-3156** [comment]
Hello, @sqrrrl 

I fixed it. I checked these samples with `ruby 2.0.0p648`.

**Pull request merged**
