### PR TITLE
Allow abnormal page token cases for paging methods

### PR DESCRIPTION
**Pull request by tcoffee-google**
Addresses googleapis/toolkit#692.

Manual changes are in:
lib/google/apis/core/base_service.rb
spec/google/apis/core/service_spec.rb

### CODE REVIEW

**Comment by tcoffee-google** [comment]
Should be submitted concurrently with https://github.com/googleapis/toolkit/pull/986.

**Comment by saicheems** [comment]
Could you explain, roughly, what's going on w/ the changes in `base_service` and `service_spec` so I can understand a bit better?

**Comment by tcoffee-google** [comment]
In the Ruby client, the `fetch_all` method handles internally the extraction of the page token from the response, but the caller handles passing this page token to the next request. I think the purpose of the changes here is made clearer by looking at the corresponding changes in https://github.com/googleapis/toolkit/pull/986.

**Comment by tcoffee-google** [comment]
Any further comments on this?

**Comment by saicheems** [comment]
lgtm

**Pull request merged**
