### PR TITLE
Add Ruby 2.5 support

### PR DESCRIPTION
**Pull request by sponomarev**
Hi there!

Accordingly, to this commit https://github.com/ruby/ruby/commit/0078e40115fd53e2cafd4e8cfb6ff5fd7f87c3db, multiline headers are no more acceptable.  It's a pity, but the library generates `User-Agent`  with OS version which contains trailing newline. 

This PR solves the issue and add explicit Ruby 2.4 and 2.5 support to test against on CI.

### CODE REVIEW

**Comment by brchristian** [comment]
@sqrrrl This issue with Ruby 2.5 compatibility which this PR addresses is a showstopper for us and for anyone trying to use the `google-api-ruby-client` gem with Ruby 2.5 (and higher). Let me know if there is anything we can do to help get this PR merged!

**Comment by sponomarev** [comment]
I signed it!

**Comment by hasghari** [comment]
Any resolution to this issue?

**Comment by sponomarev** [comment]
Hey @grant, sorry for bugging you! Any chance that it could be merged? A lot of production projects are suffering...

**Pull request merged**
