### PR TITLE
maintenance mode notice

### PR DESCRIPTION
**Pull request by danoscarmike**
Add notice to top of README to highlight that this library is in maintenance mode only (i.e. not under active development).

### CODE REVIEW

**Comment by danoscarmike** [comment]
@remi @geigerj could you please review?

**Comment by benoittgt** [comment]
I'm sorry but why it's in maintenance mode? 🤔

**Comment by saicheems** [comment]
The library has been in maintenance mode for some time - we will continue to support it as we have (client library updates, bug fixes, etc.). This is just spelling out expectations, since we'd like new users to build with the more idiomatic and actively developed [google-cloud-ruby](https://github.com/GoogleCloudPlatform/google-cloud-ruby) client.

**Comment by TrevorHinesley** [comment]
@saicheems I've looked and I don't see how https://github.com/GoogleCloudPlatform/google-cloud-ruby integrates with GMail like this client. Does it?

**Comment by saicheems** [comment]
google-cloud-ruby will not integrate with GMail because it is not a Google Cloud API, you should use this library for that use case.

**Pull request merged**
