### PR TITLE
Update README.md

### PR DESCRIPTION
**Pull request by saicheems**

### CODE REVIEW

**Comment by saicheems** [comment]
+@omaray

**Comment by tcoffee-google** [comment]
I defer to @omaray, but current wording implies to me that (a) the new client library generators are inherently specific to Cloud APIs, and (b) the old Ruby libraries are unidiomatic (which I'd argue is selling them short).

**Comment by omaray** [comment]
Node.js uses similar language. It worked out. Let's update as-is and always revisit if need be.

**Comment by saicheems** [comment]
Edited the language to match what's on `google-cloud-nodejs`. Feel free to ping me or make a PR to change the wording. I'll roll with this for now.

**Pull request merged**
