### PR TITLE
Regen APIs

### PR DESCRIPTION
**Pull request by saicheems**

### CODE REVIEW

**Comment by saicheems** [comment]
I ran
`./scripts/generate`
and `cp api_names_out.yaml api_names.yaml`

Is that correct?

**Comment by saicheems** [comment]
@sqrrrl 

Do you know what's going on with the nokogiri dependency and how I might be able to fix that? I'm not very familiar with the Ruby build system...

**Comment by valeriucraciun** [comment]
Hi,

Any idea when this pull request will get merged?
The current version 0.9.20 is several months old and out of dated.

Best,
Vali

**Comment by saicheems** [comment]
@valeriucraciun 
Hey Vali, I'll work on getting this through this week, sorry for the delay.

**Comment by austin-wang** [comment]
@saicheems were you able to figure out the `nokogiri` issue? I am encountering the same issue.

**Comment by saicheems** [comment]
@austin-wang #519 should address the build failure, will merge that soon.

**Pull request merged**
