### PR TITLE
feat: Allow disabling of the gzip decompression using client_options

### PR DESCRIPTION
**Pull request by bantini**
Addresses #636 
Added option to disable gzip decompression through client_options

### CODE REVIEW

**Comment by bantini** [comment]
@geigerj Do you think this is ready to merge? Or is there anyone else who should review it?

**Comment by geigerj** [comment]
I think this is ready to merge. @quartzmo to confirm that this new knob meets the downstream requirements.

**Comment by quartzmo** [comment]
This looks great. We are [already setting some `ClientOptions` values](https://github.com/GoogleCloudPlatform/google-cloud-ruby/blob/master/google-cloud-storage/lib/google/cloud/storage/service.rb#L48-L50), so it looks very straightforward. Of course, I won't know that it actually solves our problem (retrieving un-gzipped content) until I try it, but I'll do that as soon as I can.

**Comment by quartzmo** [comment]
Sorry, I meant: retrieving the gzipped content and having it stay gzipped.

**Comment by quartzmo** [comment]
Thank you, @bantini!

**Comment by quartzmo** [comment]
I implemented a solution for GoogleCloudPlatform/google-cloud-ruby#1835 based on this change by loading `master` branch of this library via git, and it solves our issue! When can we expect a release containing this change?

**Pull request merged**
